name: emc2_dev
channels:
  - defaults
  - conda-forge
  - pypi
dependencies:
  - sphinx
  - myst-parser
  - sphinx-material
  - make
  - numpy
  - matplotlib
  - pandas
  - scikit-image
  - imageio
  - scikit-learn