name: emc2dev
channels:
  - defaults
  - conda-forge
dependencies:
  - sphinx=8.2.3
  - myst-parser=4.0.1
  - sphinx-material=0.0.36
  - make=4.3
  - numpy
  - matplotlib
  - pandas
  - scikit-image
  - imageio
  - scikit-learn
  - pip
  - pip:
    - sphinx-copybutton